# Configurations
title:            首页
longtitle:        课程资源主页
author:           Huang Jie
email:            chezvivian@outlook.com
description: >
  Publishing class resources in my personal website. 

version:          1.0
gitbook_version:  3.2.3

url:              'https://chezvivian.github.io'
baseurl:          '/class'
rss:              RSS

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

toc:
  enabled: true
  h_min:   1
  h_max:   3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: colorful

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks
permalink:                /:title:output_ext

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/
  others:
    output: true
    permalink: /:collection/:path/
  archive:  
    output: true  
    permalink: /:collection/:path/

ordered_collections:
  - posts
  - pages
  - history
  - others

page_width: 1100px

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

future: true

# 在导航栏增加播客小镇入口（如无导航栏配置，后续补充）
navbar:
  - title: "首页"
    url: "/"
  - title: "课程资源"
    url: "/"
  - title: "播客小镇"
    url: "/podcast/"
  - title: "我的主页"
    url: "https://chezvivian.github.io"


